Allow notify-on to be in config
Netflix/metaflow pull request #1433
Opened 2023-05-24 09:01 UTC by dhpollack

Small update to the notify on feature to allow it to be set in the config.

2023-06-05 15:29 UTC, savingoyal requested changes
added a comment

2023-06-13 07:28 UTC, dhpollack commented on metaflow/metaflow_config.py
> +ARGO_EVENTS_NOTIFY_ON_ERROR = from_conf("ARGO_EVENTS_NOTIFY_ON_ERROR", False)
Is there documentation on `METAFLOW_ARGO_WORKFLOWS_CREATE_NOTIFY_ON_SUCCESS`?  I can't seem to find it nor do I see it in the code.

Made the change to use the `ARGO_WORKFLOWS` prefix.

2023-06-28 15:22 UTC, savingoyal commented on metaflow/metaflow_config.py
> +ARGO_EVENTS_NOTIFY_ON_ERROR = from_conf("ARGO_EVENTS_NOTIFY_ON_ERROR", False)
It's a feature of click. all cli arguments for metaflow are supported this way already.

2023-06-29 07:12 UTC, dhpollack commented
If this is possible without this PR then we can close this.

2023-06-29 07:12 UTC, closed without merging