feat: ability to use ServerSideEncryption for S3 uploads
Netflix/metaflow pull request #1436
Opened 2023-05-29 06:06 UTC by zendesk-klross

This PR allows users to enable Server-Side Encryption (SSE) for S3 uploads through the use of the  `METAFLOW_S3_SERVER_SIDE_ENCRYPTION` configuration setting.

See [https://github.com/Netflix/metaflow/pull/1382](url) for prior conversations regarding this issue.

2023-06-08 15:16 UTC, saikonen approved these changes

2023-06-08 15:19 UTC, saikonen requested changes
looks good and works as intended. Could you run the PR through Black formatting so the pre-commit step passes as well?

https://github.com/Netflix/metaflow/blob/master/CONTRIBUTING.md#code-style

2023-06-14 13:56 UTC, saikonen approved these changes

2023-06-15 04:07 UTC, zendesk-klross commented
@saikonen just wondering if anything else is needed from our side before we can get this merged, not sure if those failing checks are a blocker? Let us know if you need anything!

2023-06-15 16:09 UTC, merged