bug fix: unused arg for batch step --help
Netflix/metaflow pull request #1817
Opened 2024-04-29 16:44 UTC by mae5357

addresses: https://github.com/Netflix/metaflow/issues/1771

issue:

`python hello.py batch step --help` command was breaking due to wrong type for click.Choice arg.

change:

setting default arg for `ubf-context` from None to "none" in "batch step" make it compatible with [click.Choice()](https://github.com/mae5357/metaflow/blob/4e648627ea6eb6535c0e28e80ce4daf8f1839ee7/metaflow/_vendor/click/types.py#L137-L138) 

however, ubf-context is not needed for the "step" function when using aws-batch, so we can safely remove altogether.

2024-04-29 17:22 UTC, madhur-ob approved these changes

2024-04-30 06:58 UTC, romain-intel commented
If you want to keep the functionality, the proper line should read something like: 
```
type=click.Choice(["none", UBF_CONTROL, UBF_TASK]),
```
I was under the impression that ubf may be used by parallel so may be worth keeping around.

2024-05-02 17:26 UTC, mae5357 commented
@romain-intel i can revert to if you want https://github.com/Netflix/metaflow/pull/1817/commits/244ff31c9c81ac811ef4b4499c4f819e74a028f3

> I was under the impression that ubf may be used by parallel so may be worth keeping around.


fwiw, the `step()` function this is decorating doesn't take `ubf-context` as an argument. So there's not a possibility this arg is being used ([here](https://github.com/Netflix/metaflow/blob/4e648627ea6eb6535c0e28e80ce4daf8f1839ee7/metaflow/plugins/aws/batch/batch_cli.py#L210)).

2024-05-08 13:58 UTC, saikonen commented
Finally had time to test this, and as Romain mentioned, `@parallel` somewhat depends on the option existing, even if it is not explicitly used. Removing the option completely breaks parallel deco on batch. 

Can you instead revert to the commit you mentioned? Also replace the TODO with for example the following:

```
# NOTE: ubf-context is not explicitly used, but @parallel decorator tries to pass this so keep it for now.
```

2024-05-08 14:01 UTC, saikonen requested changes

2024-05-08 14:01 UTC, saikonen commented on metaflow/plugins/aws/batch/batch_cli.py
> -@click.option("--ubf-context", default=None, type=click.Choice([None, "ubf_control"]))
removing this completely leads to `@parallel` breaking on batch. Keep the original fix instead and change comment to

```
# NOTE: ubf-context is not explicitly used, but @parallel decorator tries to pass this so keep it for now.
```

2024-05-08 19:08 UTC, saikonen approved these changes

2024-05-08 19:09 UTC, merged