Add static and runtime dag info, API to fetch ancestor tasks
Netflix/metaflow pull request #2124
Opened 2024-10-31 09:07 UTC by talsperre

Add runtime DAG info so that we can query the ancestor and successor tasks for a given task easily.

2024-11-11 09:56 UTC, saikonen commented on metaflow/metadata/metadata.py
> +
is there a need for the private method, or could this simply be contained in the public-facing one? right now its not doing anything before calling the private one.

2024-11-11 09:56 UTC, saikonen commented on metaflow/metadata/metadata.py
> +
also, did you have an implementation of this for `service.py` yet?

2024-11-11 09:56 UTC, saikonen commented on metaflow/metadata/metadata.py
> +        # TODO: Do we need to do anything wrt to task attempt?
probably not, as the ancestors for task attempts should be identical, right? What about the `immediate_siblings` though, will they include or exclude attempts of the same task?

2025-01-13 20:25 UTC, romain-intel reviewed
A few comments. I think it's pretty close though. I haven't looked at hte metadata service changes. We may also want to raise a better error message if the service is not new enough?

2025-01-13 20:25 UTC, romain-intel commented on metaflow/client/core.py
> +    def _get_task_for_queried_step(self, flow_id, run_id, query_step):
Could this function simply be replaced by `Step(flow_id/run_id/step_name).task`? It doesn't seem to bring much more to it.

2025-01-13 20:25 UTC, romain-intel commented on metaflow/client/core.py
> +            field_value = self.metadata_dict.get(field_name)
We don't currently cache metadata_dict so either we could fix that or cache it here to avoid making multiple calls to the metadata service and then sorts. It would need to be cached across _get_related_tasks and this function.

2025-01-13 20:25 UTC, romain-intel commented on metaflow/client/core.py
> +                # foreach-indices value of current task
nit: foreach-indices-truncated value of the current task

2025-01-13 20:25 UTC, romain-intel commented on metaflow/client/core.py
> +        start_time = time.time()
not used -- can strip or use.

2025-01-13 20:25 UTC, romain-intel commented on metaflow/client/core.py
> +        cur_time = time.time()
not used -- can strip or use.

2025-01-13 20:25 UTC, romain-intel commented on metaflow/client/core.py
> +        Returns a dictionary of closest sibling task pathspecs of this task for each
closest sibling is confusing: I think you just mean siblings as in: tasks with the same parent.

2025-01-13 20:25 UTC, romain-intel commented on metaflow/client/core.py
> +        if len(foreach_stack) == 0:
For a user exposed function called immediate_siblings, we should handle the static case too ideally (or just change the name to make it clear it's just for foreach). For example, if I have A -> B/C/D -> E, I would expect that in B, I could get the siblings C and D. Similarly, even if I am not a new foreach split, something like A -> foreach B -> C/D/E -> BJoin -> AJoin, from C, I should get D and E (the right ones). I think this function is excluding those right?

2025-01-13 20:25 UTC, romain-intel commented on metaflow/metadata_provider/metadata.py
> +        List[str]
Is this always task_ids? Since we are making this visible to the user, it should be task_name if the user visible task identifier is the name. Basically if the task is known as 123 to the user, it should return that but if it is known as task-123, it should return that.

2025-01-13 20:25 UTC, romain-intel commented on metaflow/metaflow_config.py
> +INCLUDE_FOREACH_STACK = from_conf("INCLUDE_FOREACH_STACK", True)
We should probably change this at some point and remove it to not make it optional anymore.

2025-01-13 20:25 UTC, romain-intel commented on metaflow/plugins/metadata_providers/local.py
> +                if not task_id:
when does this happen? Also, task_id of zero is valid iirc.

2025-01-13 20:25 UTC, romain-intel commented on metaflow/plugins/metadata_providers/local.py
> +            json_files = glob.glob(os.path.join(path, "*.json"))
we should be able to do a more efficient globbing so we don't have to filter by field_prefix later on. SOmething like `f"{field_prefix}*.json"`.

2025-01-13 20:25 UTC, romain-intel commented on metaflow/task.py
> +                    MetaDatum(
I believe this is only used in the siblings thing. If that's the case, we may be able to get rid of this when we refactor the siblings thing (if we do that). I am also a little confused as to why this is needed.

2025-01-13 20:25 UTC, romain-intel commented on metaflow/task.py
> +                                field="previous_steps",
nit: consistency here between previous_steps and foreach-indices for example.

2025-01-14 16:16 UTC, saikonen commented on metaflow/plugins/metadata_providers/service.py
> +        return cls._request(cls._monitor, url, "GET")
getting an error with this that `cls` does not have `_monitor`. All other calls to `_request` pass in `None`

2025-01-14 16:16 UTC, saikonen commented on metaflow/plugins/metadata_providers/service.py
> +        url = f"{url}/tasks?{urlencode(query_params)}"
missing import for urlencode. f-strings are probably fine by 2025, as we've gotten rid of the older tests that break with them.

2025-01-14 16:27 UTC, romain-intel commented on metaflow/plugins/metadata_providers/service.py
> +        url = f"{url}/tasks?{urlencode(query_params)}"
Ya, I was wondering about fstrings but did check and our official minimum version is 3.6 which supports it -- and yes, let's move at least a tad into the future :). I'm going to start using them too and the code will slowly migrate to it (and become infinitesimally faster :) )

2025-01-14 18:19 UTC, talsperre commented on metaflow/plugins/metadata_providers/service.py
> +        return cls._request(cls._monitor, url, "GET")
Yes, I will pass in `None` simply.

2025-01-14 18:20 UTC, talsperre commented on metaflow/task.py
> +                    MetaDatum(
Will refactor siblings function mostly to return siblings irrespective of whether it is in a for each or not.

2025-01-14 18:21 UTC, talsperre commented on metaflow/client/core.py
> +    def _get_task_for_queried_step(self, flow_id, run_id, query_step):
Wasn't aware that this returns the first available task.

2025-01-16 08:53 UTC, romain-intel commented on metaflow/client/core.py
> +        return self._metadata_dict
Note: this slightly changes the syntax since now if there is new metadata, the user won't get it. Should check if this impacts other operations. Or scope the caching to just the functions that need it.

2025-01-16 11:39 UTC, saikonen requested changes

2025-01-16 11:39 UTC, saikonen commented on metaflow/client/core.py
> +        steps = (
huge problem here which leads to the queries not working correctly:
the steps ends up being of type `str` on OSS metadata-service, so using these you end up iterating over characters instead of step names, e.g.:

```
/flows/SplitFlow/runs/63/steps/{/filtered_tasks?metadata_field_name=foreach-indices&metadata_field_value=%7B%7D&query_step=%7B
/flows/SplitFlow/runs/63/steps/e/filtered_tasks?metadata_field_name=foreach-indices&metadata_field_value=%7B%7D&query_step=e
/flows/SplitFlow/runs/63/steps/n/filtered_tasks?metadata_field_name=foreach-indices&metadata_field_value=%7B%7D&query_step=n
/flows/SplitFlow/runs/63/steps/d/filtered_tasks?metadata_field_name=foreach-indices&metadata_field_value=%7B%7D&query_step=d
/flows/SplitFlow/runs/63/steps/}/filtered_tasks?metadata_field_name=foreach-indices&metadata_field_value=%7B%7D&query_step=%7D

```

2025-01-28 18:24 UTC, savingoyal commented on metaflow/client/core.py
> +    def immediate_ancestors(self) -> Dict[str, List[str]]:
can we offer a property `parents` which simply returns a list of task pathspecs. it will return `None`for the `start` step. an open question is if we would want to also offer `parent` - maybe we can cross that bridge as a follow up PR if needed.

2025-01-28 18:26 UTC, savingoyal commented on metaflow/client/core.py
> +    def immediate_successors(self) -> Dict[str, List[str]]:
can we offer a property `children` which simply returns a list of task pathspecs. it will return `None` for the `end` step. similar comment for `child` as for `parent`

2025-01-28 18:28 UTC, savingoyal commented on metaflow/client/core.py
> +    def immediate_ancestors(self) -> Dict[str, List[str]]:
what are the consistency guarantees offered by this property. do we expect that this property will return an immutable set of parents as soon as this task is registered?

2025-01-28 18:29 UTC, savingoyal commented on metaflow/client/core.py
> +    def immediate_successors(self) -> Dict[str, List[str]]:
what is the expected behavior of this property? as soon as children task are registered, do we start updating the `children` property? also, when do we know that there are not going to be any more children tasks?

2025-01-28 18:33 UTC, savingoyal commented on metaflow/client/core.py
> +    def siblings(self) -> Dict[str, List[str]]:
can this be `siblings(self, ancestors)` - where `ancestors` is a list of task pathspec and defaults to `task.parents`?

2025-01-28 18:38 UTC, savingoyal commented on metaflow/client/core.py
> +    def immediate_ancestors(self) -> Dict[str, List[str]]:
also - we are assuming that return values here point to the latest successful attempt. might be good to note this in the doc string.

2025-01-28 18:44 UTC, savingoyal commented on metaflow/task.py
> +            # Add runtime dag info - for a nested foreach this may look like:
in terms of metadata that needs to be stored - we could simply stringify the stack and store it - `step1:0,step2:1...` - and that should be it, no? a prefix query should be fast enough

2025-02-04 21:03 UTC, savingoyal requested changes

2025-02-04 21:03 UTC, savingoyal commented on metaflow/client/core.py
> +    def _get_metadata_query_vals(
```   
  def _iter_matching_tasks(self, steps, pattern):
        """
        Yield tasks from specified steps matching a foreach path pattern.

        Parameters
        ----------
        steps : List[str]
            List of step names to search for tasks
        pattern : str
            Regex pattern to match foreach-indices metadata

        Returns
        -------
        Iterator[Task]
            Tasks matching the foreach path pattern
        """
        flow_id, run_id, _, _ = self.path_components
        
        for step in steps:
            task_ids = self._metaflow.metadata.filter_tasks_by_metadata(
                flow_id, run_id, step, "foreach-indices", pattern
            )
            for task_id in task_ids:
                yield Task(
                    pathspec="%s/%s/%s/%s" % (flow_id, run_id, step, task_id),
                    _namespace_check=False
                )
```

2025-02-07 22:00 UTC, romain-intel reviewed
not a review -- just some comments.

2025-02-07 22:00 UTC, romain-intel commented on metaflow/client/core.py
> +    def _get_metadata_query_vals(
Why couldn't the filter_task_by_metadata return all the info we need to form the task? It seems it would save a few RT calls right?

2025-02-12 20:45 UTC, savingoyal requested changes

2025-02-12 20:45 UTC, savingoyal commented on metaflow/client/core.py
> +        target_path = target_task.metadata_dict.get("foreach-execution-path", "")
nit - just `target_task.metadata_dict.get("foreach-execution-path")`

2025-02-12 20:45 UTC, savingoyal commented on metaflow/client/core.py
> +        current_path = self.metadata_dict.get("foreach-execution-path", "")
nit - just `self.metadata_dict.get("foreach-execution-path")` - just to guard against an eventuality where foreach-execution-path set to empty starts having a meaning.

2025-02-12 20:45 UTC, savingoyal commented on metaflow/client/core.py
> +    def parent_tasks(self) -> List["Task"]:
would be good to handle the case where the user is inspecting a task that ran using an old version of metaflow or is using an old version of the service...

2025-02-12 20:45 UTC, savingoyal commented on metaflow/client/core.py
> +    def _iter_matching_tasks(self, steps, pattern):
minor nit - `_iter_matching_tasks(self, steps, metadata_key, metadata_pattern)`

2025-02-12 20:45 UTC, savingoyal commented on metaflow/client/core.py
> +        attempt.
parents should be the same across attempts?

2025-02-12 20:45 UTC, savingoyal commented on metaflow/client/core.py
> +        attempt.
nit - `if one exists`

2025-02-12 20:45 UTC, savingoyal commented on metaflow/client/core.py
> +            return []
why not an empty return?

2025-02-12 20:45 UTC, savingoyal commented on metaflow/client/core.py
> +    def parent_steps(self) -> List[str]:
we can return the step object instead of a str

2025-02-12 20:45 UTC, savingoyal commented on metaflow/client/core.py
> +                previous_nodes.append(node_name)
yield to maintain consistency?

2025-02-12 20:45 UTC, savingoyal commented on metaflow/client/core.py
> +    def child_steps(self) -> List[str]:
same comments as above

2025-02-12 20:45 UTC, savingoyal commented on metaflow/metadata_provider/metadata.py
> +        query_step: str,
nit - `step_name`

2025-02-12 20:45 UTC, savingoyal commented on metaflow/plugins/metadata_providers/local.py
> +            task_name = task.get("task_name")
curious - why `task_name`?

2025-02-12 20:45 UTC, savingoyal commented on metaflow/task.py
> +            foreach_execution_path = self._dynamic_runtime_metadata(foreach_stack)
[this](https://github.com/Netflix/metaflow/pull/2124/files#r1941819183) comment still applies

2025-02-12 20:45 UTC, savingoyal commented on test/core/tests/client_child_tasks.py
> +class ChildrenTest(MetaflowTest):
you can combine these two tests together.

2025-02-12 20:45 UTC, savingoyal commented on test/core/tests/client_child_tasks.py
> +                    assert task.pathspec in child_task.data.parent_pathspecs, (
can you verify other properties as well?

2025-02-19 08:46 UTC, talsperre commented on metaflow/plugins/metadata_providers/local.py
> +            task_name = task.get("task_name")
Addressed.

2025-02-20 17:35 UTC, savingoyal requested changes

2025-02-20 17:35 UTC, savingoyal commented on metaflow/client/core.py
> +
this code block can be within the service implementation and not in the client. the client shouldn't have to bother about the actual implementation semantics of metadata.

2025-02-20 17:35 UTC, savingoyal commented on metaflow/client/core.py
> +    def parent_steps(self) -> Optional["Step"]:
the same property is duplicated in L:1989?

2025-02-20 17:35 UTC, savingoyal commented on metaflow/client/core.py
> +    def parent_steps(self) -> Optional["Step"]:
returns an optional list of steps

2025-02-20 17:35 UTC, savingoyal commented on metaflow/client/core.py
> +    def child_steps(self) -> "Step":
returns an optional list of steps

2025-02-20 17:35 UTC, savingoyal commented on metaflow/exception.py
> +class ServiceException(MetaflowException):
why move this here? - this is tied to the service implementation and ideally shouldn't be pulled into the core

2025-02-20 17:35 UTC, savingoyal commented on metaflow/client/core.py
> +    ServiceException,
superfluous?

2025-02-20 17:35 UTC, savingoyal commented on metaflow/metadata_provider/metadata.py
> +        flow_id: str,
nit - we use `flow_name`

2025-02-20 17:35 UTC, savingoyal commented on metaflow/task.py
> +    def _dynamic_runtime_metadata(foreach_stack):
please move this in-line in L:514

2025-02-20 17:35 UTC, savingoyal commented on test/core/contexts.json
>                  "--tag=\u523a\u8eab means sashimi",
you can exclude black from touching files that are not in the git commit

2025-02-20 17:35 UTC, savingoyal commented on test/core/tests/runtime_dag_tests.py
> +from metaflow_test import MetaflowTest, ExpectationFailed, steps
nit - file can be named runtime_dag.py to maintain parity with existing convention

2025-02-20 17:35 UTC, savingoyal commented on test/core/tests/runtime_dag_tests.py
> +class RuntimeDagTests(MetaflowTest):
nit - just `RuntimeDagTest`

2025-02-20 17:35 UTC, savingoyal commented on test/core/tests/runtime_dag_tests.py
> +        from metaflow import Task
superfluous?

2025-02-20 18:08 UTC, talsperre commented on metaflow/metadata_provider/metadata.py
> +        flow_id: str,
Will change it to `flow_name` - I did see `flow_id` in a bunch of different places in `local.py` though.

2025-02-20 18:15 UTC, talsperre commented on metaflow/client/core.py
> +
If the endpoint does not exist in the metadata service then how do you even return that error message?

2025-02-20 18:18 UTC, savingoyal commented on metaflow/client/core.py
> +
this try-except block can be in service.py rather than in the client.

2025-02-20 19:22 UTC, savingoyal commented on metaflow/client/core.py
> +    def parent_steps(self) -> Iterator["Step"]:
this is still duplicated?

2025-02-20 19:24 UTC, savingoyal commented on metaflow/plugins/metadata_providers/service.py
> +                    "Upgrade to a newer version of Metadata service to use this feature."
can you add the metaflow service version that they need to upgrade to? basically if the latest is 2.3.4, then, have a message that says upgrade to >=2.4.0

2025-02-20 19:24 UTC, savingoyal commented on metaflow/plugins/metadata_providers/service.py
> +                    "Upgrade to a newer version of Metadata service to use this feature."
cc @saikonen to bump the version of metaflow-service when the endpoint is released.

2025-02-20 19:25 UTC, talsperre commented on metaflow/client/core.py
> +    def parent_steps(self) -> Iterator["Step"]:
Wait, I didn;t push this change. Let me do that.

2025-02-20 21:40 UTC, merged