Unbounded foreach
Netflix/metaflow pull request #450
Opened 2021-03-12 17:55 UTC by romain-intel

2021-03-19 21:14 UTC, romain-intel reviewed
A few comments mostly related around cleanup. LGTM otherwise.

2021-03-19 21:14 UTC, romain-intel commented on metaflow/runtime.py
> +			# statically inferred transitions. Make an exception for control
Nit: indentation issue.

2021-03-19 21:14 UTC, romain-intel commented on metaflow/runtime.py
> +                    # combination with other decorators (e.g. `@archer`) only to
Internal comment needs rewording.

2021-03-19 21:14 UTC, romain-intel commented on metaflow/runtime.py
> +									  self.task.ubf_context)
Nit: Indentation

2021-03-19 21:14 UTC, romain-intel commented on metaflow/util.py
>                  if not isinstance(value, bool):
Internal PR had a to_unicode here. Is this no longer relevant?

2021-04-09 22:33 UTC, romain-intel commented
@seeravikiran: could you make the small changes suggested and then we can merge if that's ok.

2021-04-20 04:31 UTC, savingoyal commented
@romain-intel Is this PR linked to datastore changes or can I go ahead and test this PR on top of master?

2021-04-20 04:34 UTC, savingoyal requested changes

2021-04-20 04:34 UTC, savingoyal commented on metaflow/plugins/__init__.py
> +                                TestUnboundedForeachDecorator], ext_plugins.STEP_DECORATORS, 'name')
I don't think we should expose this decorator right now.

2021-04-22 20:35 UTC, romain-intel commented
I think you can port this PR on top of master. I don't think it has a strong dependency (but things will change a bit).

2021-06-23 16:56 UTC, romain-intel commented
Replaced by #554

2021-06-23 16:56 UTC, closed without merging