Allow for more flexible (escaped) variable names in CLI options
Netflix/metaflow pull request #495
Opened 2021-04-28 10:42 UTC by romain-intel

2021-04-28 17:40 UTC, savingoyal commented on metaflow/util.py
> +                    if value.lstrip("\\").startswith("$"):
@romain-intel Can we leave a comment in the code about this change so that a future commit doesn't end up reverting it.

2021-04-28 17:40 UTC, savingoyal requested changes
Added a minor comment. Feel free to merge.

2021-04-30 00:21 UTC, romain-intel commented
Will merge after tests if no other action.

2021-04-30 01:10 UTC, savingoyal approved these changes

2021-04-30 01:10 UTC, merged