allow to mount host volumes in AWS Batch
Netflix/metaflow pull request #640
Opened 2021-08-11 23:00 UTC by oavdeev

# What does this PR do?

Adds an option to `@batch` decorator to mount host volumes inside the container. `@batch(mount_host_volumes="/mnt/")`. This way, `/mnt` from host will be mounted at `/mnt` inside the container. This (partially) addresses #441

In this release this is considered an _advanced_ feature due to less friendly UX and the fact that troubleshooting this requires a decent knowledge of AWS Batch. 

I've tested this on Batch and Step Functions and it seems to work!

## Potential improvements in future PRs, not included here

* First class support for EFS mounts (not included because the configuration is pretty hairy, needs some thinking)
* Support for customizing mount points inside a container

2021-08-17 17:22 UTC, corleyma commented
While a good start, I think this implementation falls short for a couple of reasons:
- as mentioned, not being able to set the mount path inside the container seems like a strange limitation, and will likely place a burden on application developers to change their applications to fit the details of the infrastructure.
- including this in `@batch` means it can only be used in flows that are forced to run a particular step on Batch (or else in every step if using `with` syntax)
  - it seems a more natural way for this to work would be some mechanism to specify these Batch-specific resource definitions in `@resources` (either as nested configs, or else as part of an `@batch_resources` decorator).
    - Combined with the ability to set the container mount path, this should make it easy to have local runs (e.g. for integration tests) that work seamlessly with remote runs in production.
    - This desire to define Batch-specific resources arises in other contexts, e.g. the desire to set a per-step job queue without forcing the step to run on Batch.  Figuring out the idiom for this configuration in Metaflow and embracing it for all such configs would really increase the flexibility.

2021-08-17 21:56 UTC, oavdeev commented
Good points, tbh this PR was intended to solve a pretty narrow (advanced) use case of mounting EFS/FSx volumes from host into the container.

Re: local runs, wouldn't you have to fork the logic? You'd have to remember that the step may run in local mode and make sure to branch, something like:

```python
@resources(batch_mount_points=["/mnt"])
def step_foo(self):
    if os.path.exists("/mnt"):
         # running on Batch
        model = load_model("/mnt/foo.tar.gz")
    else:
        # running locally
        model = MockLocalModel()
...
```

In this sense, one benefit of keeping it in `@batch` like in this PR that the UX is more foolproof; you're guaranteed that the step will run on Batch and `/mnt` will be there. I do see the benefit of being able to run the code locally without changing the annotation though.

2021-08-18 05:34 UTC, popsonebz commented
Thanks @oavdeev. I am hoping this PR gets merged as I need this feature for similar use case. Were you able to test this on AWS metaflow deployment? If yes, Kindly share the steps so I can replicate it. Thanks

2021-08-19 15:05 UTC, savingoyal requested changes
PR LGTM! Can we replace `mount_host_volumes` with `host_volumes` before shipping it?

2021-08-20 15:40 UTC, merged