fixed cli command when task_id provided
Netflix/metaflow pull request #890
Opened 2022-01-12 16:17 UTC by zhugejun

Fix https://github.com/Netflix/metaflow/issues/816

2022-01-13 23:55 UTC, savingoyal requested changes

2022-01-13 23:55 UTC, savingoyal commented on metaflow/cli.py
> +                obj.flow_datastore,
@zhugejun The signature for the constructor is different for TaskDataStore. This PR actually fails to address #816 at the moment. 

```
Traceback (most recent call last):
  File "/Users/savin/Code/metaflow/metaflow/cli.py", line 1110, in main
    start(auto_envvar_prefix="METAFLOW", obj=state)
  File "/Users/savin/opt/miniconda3/envs/py3/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(args, kwargs)
  File "/Users/savin/opt/miniconda3/envs/py3/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/savin/opt/miniconda3/envs/py3/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/savin/opt/miniconda3/envs/py3/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, ctx.params)
  File "/Users/savin/opt/miniconda3/envs/py3/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(args, kwargs)
  File "/Users/savin/opt/miniconda3/envs/py3/lib/python3.7/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, args, kwargs)
  File "/Users/savin/Code/metaflow/metaflow/cli.py", line 347, in logs
    allow_unsuccessful=True,
TypeError: __init__() got an unexpected keyword argument 'allow_unsuccessful'
```

2022-01-14 01:29 UTC, zhugejun commented on metaflow/datastore/__init__.py
> +from .task_datastore import TaskDataStore
Well, if this isn't needed, how do I use `TaskDataStore` in `cli.py`?

2022-01-14 01:36 UTC, savingoyal commented on metaflow/datastore/__init__.py
> +from .task_datastore import TaskDataStore
You are already importing it in `cli.py`

2022-01-14 02:05 UTC, savingoyal commented on metaflow/datastore/__init__.py
> +from .task_datastore import TaskDataStore
Ah yes, you are right.

2022-01-14 02:06 UTC, savingoyal commented
Will merge as soon as tests pass.

2022-01-17 21:24 UTC, merged